name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

env:
  default_php: 8.4

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: shivammathur/setup-php@2.34.1
        with:
          php-version: ${{ env.default_php }}
          coverage: none
      - uses: ramsey/composer-install@v3
      - run: composer lint
      - run: composer cs-check

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: shivammathur/setup-php@2.34.1
        with:
          coverage: none
          php-version: ${{ env.default_php }}
      - uses: ramsey/composer-install@v3
      - run: php vendor/bin/phpstan analyse

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4']

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: shivammathur/setup-php@2.34.1
        with:
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - uses: ramsey/composer-install@v3
      - run: ./vendor/bin/phpunit
      - uses: codecov/codecov-action@v1

  rector:
    runs-on: ubuntu-latest
    name: Run Rector on PHP
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: shivammathur/setup-php@2.34.1
        with:
          php-version: ${{ env.default_php }}
          tools: composer
      - uses: ramsey/composer-install@v3
      - run: composer rector
