name: Static Analysis

on: [push, pull_request]

jobs:
  static-analysis-phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: "${{ matrix.php-version }}"
          tools: cs2pr

      - name: Install dependencies with composer
        run: composer update --no-progress --no-suggest --no-interaction --prefer-dist

      - name: Run a static analyses with phpstan
        run: php vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
